logging.level.kroonprins.mocker: info

management:
  endpoint:
    mappings.enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env,shutdown,mappings

#mocker.metrics.enabled: false